#pragma once
#include "platform/platform_header.h"
#include "input/input.h"



// See: https://developer.android.com/ndk/reference/group/input
static constexpr Key MappedKeycodes[] =
{
    Key::None, // Unknown,
    Key::None, // Soft Left,
    Key::None, // Soft Right,
    Key::None, // Home,
    Key::None, // Back,
    Key::None, // Call,
    Key::None, // End Call,
    Key::None, // 0,
    Key::None, // 1,
    Key::None, // 2,
    Key::None, // 3,
    Key::None, // 4,
    Key::None, // 5,
    Key::None, // 6,
    Key::None, // 7,
    Key::None, // 8,
    Key::None, // 9,
    Key::None, // Star,
    Key::None, // Pound,
    Key::Up, // DPAD Up,
    Key::Down, // DPAD Down,
    Key::Left, // DPAD Left,
    Key::Right, // DPAD Right,
    Key::None, // DPAD Center,
    Key::None, // Volume Up,
    Key::None, // Volume Down,
    Key::None, // Power,
    Key::None, // Camera,
    Key::None, // Clear,
    Key::A, // A,
    Key::B, // B,
    Key::C, // C,
    Key::D, // D,
    Key::E, // E,
    Key::F, // F,
    Key::G, // G,
    Key::H, // H,
    Key::I, // I,
    Key::J, // J,
    Key::K, // K,
    Key::L, // L,
    Key::M, // M,
    Key::N, // N,
    Key::O, // O,
    Key::P, // P,
    Key::Q, // Q,
    Key::R, // R,
    Key::S, // S,
    Key::T, // T,
    Key::U, // U,
    Key::V, // V,
    Key::W, // W,
    Key::X, // X,
    Key::Y, // Y,
    Key::Z, // Z,
    Key::None, // Comma,
    Key::None, // Period,
    Key::None, // Alt Left,
    Key::None, // Alt Right,
    Key::LeftShift, // Shift Left,
    Key::None, // Shift Right,
    Key::None, // Tab,
    Key::None, // Space,
    Key::None, // Sym,
    Key::None, // Explorer,
    Key::None, // Envelope,
    Key::None, // Enter,
    Key::None, // Del,
    Key::None, // Grave,
    Key::None, // Minus,
    Key::None, // Equals,
};